### PR TITLE
Lab5

### PR DESCRIPTION
**Pull request by thast**
Refactoring of Lab5:
-Merge two notebook in 1
-numbered sections for clarity
-fix some typos and bugs
-remove old links and update with new for binders and GPG

### CODE REVIEW

**Comment by thast** [comment]
"jupyter_client.kernelspec.NoSuchKernel: No such kernel named Python [Root]"

Python [Root] is indeed the name of my Kernel on my windows machine... Any idea how to overcome this? @lheagy

**Comment by lheagy** [comment]
hey @thast : try kernel clear and run all, then save and commit

**Comment by lheagy** [comment]
I would suggest keeping the two notebooks seperate. They are both accomplishing different things (NMO, normal incidence seismogram). Thoughts @dougoldenburg ?

**Comment by thast** [comment]
Merging them was one of the feedback from the student last year. Some were confused of which app (or which notebook) to use. My idea was to merge the notebook but to improve the numbering and references so Lab pdf and notebook are consistent with each other.

**Comment by lheagy** [comment]
Ok, I think the confusion can be solved through instructions and improved titles rather than merging the two notebooks. Please chat with @dougoldenburg before merging this pull request

**Pull request merged**
